name: school_dashboard
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.2
  conditional_builder_null_safety: ^0.0.6


  dio: ^5.1.1
  web_socket_channel: ^2.4.0
  shared_preferences: ^2.1.0

  email_validator: ^2.1.17

  simple_animations: ^4.2.0
  flutter_spinkit: ^5.2.0

  fluttertoast: ^8.2.1

  flutter_admin_scaffold: ^1.1.2
  syncfusion_flutter_charts: ^21.2.4
  dropdown_button2: ^2.1.2
  #simple_animations: ^5.0.0+3
  lottie: ^2.3.2
  table_calendar: ^3.0.9
  animated_text_kit: ^4.2.2
  flutter_staggered_animations: ^1.1.1
  data_table_2: ^2.3.12
  awesome_dialog: ^3.1.0

  number_paginator: ^0.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0



flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

